export const LOCATION_POSITION_REQUEST = 'LOCATION_POSITION_REQUEST'
export const LOCATION_POSITION_SUCCESS = 'LOCATION_POSITION_SUCCESS'
export const LOCATION_POSITION_FAIL = 'WEATHER_POSITION_FAIL'

export const LOCATION_INFO_REQUEST = 'LOCATION_INFO_REQUEST'
export const LOCATION_INFO_SUCCESS = 'LOCATION_INFO_SUCCESS'
export const LOCATION_INFO_FAIL = 'WEATHER_INFO_FAIL'

export const WEATHER_INFO_REQUEST = 'WEATHER_INFO_REQUEST'
export const WEATHER_INFO_SUCCESS = 'WEATHER_INFO_SUCCESS'
export const WEATHER_INFO_FAIL = 'WEATHER_INFO_FAIL'
