export { default as Navbar } from './Navbar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as Info } from './Info/Info'
export { default as Review } from './ReviewC/Review'
export { default as PricesPlans } from './PricesPlans/PricesPlans'
export { default as Footer } from './Footer/Footer'
